name: Firebase Hosting CI/CD

on:
  push:
    branches:
      - main  # main 브랜치에 push할 때마다 배포

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # 사용하는 Node.js 버전

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          npm install
          npm run build  # React 앱 빌드

      # 4. Set up Firebase CLI
      - name: Set up Firebase CLI
        uses: wzieba/Firebase-Action@v2
        with:
          firebase_token: ${{ secrets.FIREBASE_TOKEN }}

      # 5. Deploy to Firebase Hosting
      - name: Deploy to Firebase Hosting
        run: |
          firebase deploy --only hosting --project ${{ secrets.FIREBASE_PROJECT_ID }}
